language: python
python:
 - "2.7"

install: "pip install -r requirements.txt"

before_script:
 - autopep8 -ir *.py
 - flake8 --max-complexity=10 --exclude=*.txt,*.md --max-line-length=150 *

script:
 - lettuce test/
 - python test/TestTenis.py -v
 - coverage run --branch test/TestTenis.py
 - coverage report -m

notifications: 
 email: false
